# Generated by Django 5.1.5 on 2025-03-14 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BigBuyAPI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jwttoken",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("jwttoken", models.CharField(max_length=300)),
                ("tokenexpiredtime", models.DateTimeField()),
                ("tokenstatus", models.CharField(db_default="N", max_length=1)),
                ("createdby", models.IntegerField()),
                ("createdtime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "TB_BB_JWTTOKEN",
            },
        ),
        migrations.CreateModel(
            name="UserLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("logintime", models.DateTimeField(auto_now_add=True)),
                ("logouttime", models.DateTimeField(blank=True, null=True)),
                (
                    "tokenid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BigBuyAPI.jwttoken",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="BigBuyAPI.user"
                    ),
                ),
            ],
            options={
                "db_table": "TB_BB_USERLOG",
            },
        ),
    ]
