# Generated by Django 5.1.5 on 2025-03-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BigBuyAPI", "0002_jwttoken_userlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="userid",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
